version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2221
      - POSTGRES_DB=social-network
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432"

  web:
    build: .
    expose:      
     - "8000"
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:2221@db:5432/social-network
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis
    ports:
      - "6379"

volumes:
  db-data:
